class UTME():

    def __init__(self, llm_endpoint, llm_key, llm_options = {}):
      """
        Initialize the UTME class with the specified Large Language Model (LLM) configuration.

        Parameters:
        - llm_endpoint (str): The endpoint for the LLM.
        - llm_key (str): The API key for accessing the LLM.
        - llm_options (dict): Additional options for the LLM (default is an empty dictionary).
      """
      self.llm_key = llm_key
      self.llm_endpoint = llm_endpoint
      self.llm_options = llm_options
      openai.api_key = llm_key
      openai.api_base = llm_endpoint

    def llm_prompt(self, prompt):
      """
        Perform language model (LLM) prompt completion.

        Parameters:
        - prompt (str): The user's input prompt for LLM.

        Returns:
        - response (dict): The response generated by the LLM.
      """
      response = openai.ChatCompletion.create(
          messages = [{"role": "user", "content": prompt}],
          **llm_options
      )
      return response
